
export const BMI_UPDATE_PROP = 'BMI_UPDATE_PROP'
export const BMI_UPDATE_FETCH_PREVIOUS = 'BMI_UPDATE_FETCH_PREVIOUS'

export const SIGNIN_START = 'SIGNIN_START'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAIL = 'SIGNIN_FAIL'

export const SIGNOUT_START = 'SIGNOUT_START'
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS'
export const SIGNOUT_FAIL = 'SIGNOUT_FAIL'

export const INITIALIZE_STATE = 'INITIALIZE_STATE'

export const CLEAR_USER_INFO = 'CLEAR_USER_INFO'

export const OXFORD_DICT_UPDATE_KEYWORD = 'OXFORD_DICT_UPDATE_KEYWORD'
export const OXFORD_DICT_SEARCH_START = 'OXFORD_DICT_SEARCH_START'
export const OXFORD_DICT_SEARCH_ERROR = 'OXFORD_DICT_SEARCH_ERROR'
export const OXFORD_DICT_SEARCH_SUCCESS = 'OXFORD_DICT_SEARCH_SUCCESS'
