
export const BMI_UPDATE_PROP = 'BMI_UPDATE_PROP'
export const BMI_UPDATE_FETCH_PREVIOUS = 'BMI_UPDATE_FETCH_PREVIOUS'

export const SIGNIN_START = 'SIGNIN_START'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAIL = 'SIGNIN_FAIL'

export const SIGNOUT_START = 'SIGNOUT_START'
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS'
export const SIGNOUT_FAIL = 'SIGNOUT_FAIL'

export const INITIALIZE_STATE = 'INITIALIZE_STATE'

export const CLEAR_USER_INFO = 'CLEAR_USER_INFO'

export const OXFORD_DICT_UPDATE_KEYWORD = 'OXFORD_DICT_UPDATE_KEYWORD'
export const OXFORD_DICT_SEARCH_START = 'OXFORD_DICT_SEARCH_START'
export const OXFORD_DICT_SEARCH_ERROR = 'OXFORD_DICT_SEARCH_ERROR'
export const OXFORD_DICT_SEARCH_SUCCESS = 'OXFORD_DICT_SEARCH_SUCCESS'


export const AZURE_ADD_ACCOUNT_UPDATE_PROP = 'AZURE_ADD_ACCOUNT_UPDATE_PROP'
export const AZURE_ADD_ACCOUNT_ADD = 'AZURE_ADD_ACCOUNT_ADD'
export const AZURE_ADD_ACCOUNT_ADD_START = 'AZURE_ADD_ACCOUNT_ADD_START'
export const AZURE_ADD_ACCOUNT_ADD_SUCCESS = 'AZURE_ADD_ACCOUNT_ADD_SUCCESS'
export const AZURE_ADD_ACCOUNT_ADD_ERROR = 'AZURE_ADD_ACCOUNT_ADD_ERROR'

export const AZURE_ACCOUNTS_FETCH_SUCCESS = 'AZURE_ACCOUNTS_FETCH_SUCCESS'
export const AZURE_ACCOUNTS_FETCH = 'AZURE_ACCOUNTS_FETCH'

export const AZURE_BLOB_EXPLORER_UPDATE_PROPS = 'AZURE_BLOB_EXPLORER_UPDATE_PROPS'